SET SERVEROUTPUT ON;
DECLARE
    NUMERO NUMBER :=&VALOR;
BEGIN
    IF MOD(NUMERO,2)=0 THEN
        DBMS_OUTPUT.PUT_LINE('O NÚMERO ' || NUMERO || 'INFORMADO É PAR');
    ELSE
        DBMS_OUTPUT.PUT_LINE('O NÚMERO ' || NUMERO || 'INFORMADO É IMPAR');
    END IF;
END;