SET SERVEROUTPUT ON;

DECLARE
    V_ESTADO VARCHAR2(20);
    V_PAIS VARCHAR2(20);
BEGIN

    FOR REC IN (
        SELECT A.NOME AS PAIS, B.NOME AS ESTADO FROM PAIS A INNER JOIN  ESTADO B ON (A.ID_PAIS = B.ID_PAIS)
    )
    LOOP
        V_PAIS := REC.PAIS;
        V_ESTADO := REC.ESTADO;
        dbms_output.PUT_LINE(V_PAIS || ', ' || V_ESTADO);
    END LOOP;
END;