SET SERVEROUTPUT ON;
DECLARE
    NUMERO NUMBER :=&VALOR;
BEGIN
    IF NUMERO <0 THEN
        DBMS_OUTPUT.PUT_LINE('O NÚMERO ' || NUMERO || 'INFORMADO É NEGATIVO');
    ELSE
        DBMS_OUTPUT.PUT_LINE('O NÚMERO ' || NUMERO || 'INFORMADO É POSITIVO');
    END IF;
END;